<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FinanceChartAccount;
use App\Models\FinanceIncomeHead;

class FinanceIncomeHeadSeeder extends Seeder
{
    public function run(): void
    {
        $revenueAccount = FinanceChartAccount::where('code', '4000')->first();
        if (!$revenueAccount) {
            return;
        }

        $incomeHeads = [
            // Standard Parish Receipts (Requested List)
            ['code' => 'INC-001', 'name' => 'Monthly Family Contribution', 'description' => 'Regular monthly contribution from parish families.'],
            ['code' => 'INC-002', 'name' => 'Sunday Offering', 'description' => 'Collections during Sunday Holy Qurbana services.'],
            ['code' => 'INC-003', 'name' => 'Nercha / Aanethe', 'description' => 'Traditional liturgical offerings and bread blessing collections.'],
            ['code' => 'INC-004', 'name' => 'Qurbana Panam', 'description' => 'Standard offering for Holy Qurbana intentions.'],
            ['code' => 'INC-005', 'name' => 'Special Holy Qurbana', 'description' => 'Offerings for dedicated or special intention Holy Qurbana services.'],
            ['code' => 'INC-006', 'name' => 'Madhyastha Prarthana', 'description' => 'Contributions for intercessory prayers.'],
            ['code' => 'INC-007', 'name' => 'Memorial Prayer', 'description' => 'Offerings for memorial prayers (Dhoopa Prarthana).'],
            ['code' => 'INC-008', 'name' => 'Dukhrana', 'description' => 'Special contributions for memorial feasts or Dukhrana days.'],
            ['code' => 'INC-009', 'name' => 'Baptism Offering', 'description' => 'Offerings made during the sacrament of Holy Baptism.'],
            ['code' => 'INC-010', 'name' => 'Marriage Offering', 'description' => 'Offerings made during the sacrament of Holy Matrimony.'],
            ['code' => 'INC-011', 'name' => 'Funeral Offering', 'description' => 'Offerings and contributions given during funeral services.'],
            ['code' => 'INC-012', 'name' => 'House Blessing', 'description' => 'Offerings received during home blessings.'],
            ['code' => 'INC-013', 'name' => 'Certificate Fee', 'description' => 'Fees collected for issuing certificates (baptism, marriage, membership, etc.).'],
            ['code' => 'INC-014', 'name' => 'Christmas Offering', 'description' => 'Special collections and offerings for Christmas day services.'],
            ['code' => 'INC-015', 'name' => 'Easter Offering', 'description' => 'Special collections and offerings for Easter Sunday services.'],
            ['code' => 'INC-016', 'name' => 'Great Lent Collection', 'description' => 'Dedicated collections during the Great Lent season.'],
            ['code' => 'INC-017', 'name' => 'Holy Week Collection', 'description' => 'Dedicated collections during Holy Week and Passion services.'],
            ['code' => 'INC-018', 'name' => 'Perunnal Income', 'description' => 'All collections, sponsorships, and auctions from the parish feast festival.'],
            ['code' => 'INC-019', 'name' => 'Sunday School Fee', 'description' => 'Annual Sunday School registration and activity fees.'],
            ['code' => 'INC-020', 'name' => 'Youth Association Income', 'description' => 'Income generated by or contributed to the parish Youth Association.'],
            ['code' => 'INC-021', 'name' => 'Marthamariyam Samajam Income', 'description' => 'Income generated by or contributed to the Marthamariyam Samajam (women\'s wing).'],
            ['code' => 'INC-022', 'name' => 'Building Fund', 'description' => 'Contributions dedicated to acquisition or renovation of church buildings.'],
            ['code' => 'INC-023', 'name' => 'Charity Fund', 'description' => 'Contributions raised for benevolence, educational, or medical relief.'],
            ['code' => 'INC-024', 'name' => 'Diocese Central Collection', 'description' => 'Contributions collected for or forwarded by the central diocese.'],
            ['code' => 'INC-025', 'name' => 'Non-Member Donation', 'description' => 'Donations received from visitors, non-members, or general benefactors.', 'member_default' => false],
            ['code' => 'INC-026', 'name' => 'Bank Interest', 'description' => 'Interest earned on church bank savings or fixed deposits.', 'member_default' => false],
            ['code' => 'INC-027', 'name' => 'Refund Received', 'description' => 'Refunds or cashbacks received from suppliers or services.', 'member_default' => false],
            ['code' => 'INC-074', 'name' => 'Miscellaneous Income', 'description' => 'Other minor receipts not covered elsewhere.', 'member_default' => false],
        ];

        foreach ($incomeHeads as $head) {
            FinanceIncomeHead::updateOrCreate(
                ['code' => $head['code']],
                [
                    'chart_account_id' => $revenueAccount->id,
                    'name' => $head['name'],
                    'description' => $head['description'],
                    'member_default' => isset($head['member_default']) ? $head['member_default'] : true,
                    'is_active' => true,
                ]
            );
        }
    }
}
